server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        # Auth Service
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        # User Service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**, /api/passengers/**

        # Driver Service
        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/api/drivers/**

        # Ride Service
        - id: ride-service
          uri: lb://ride-service
          predicates:
            - Path=/api/rides/**

        # Payment Service
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**

        # Notification Service
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

        # Notification WebSocket
        - id: notification-ws
          uri: lb:ws://notification-service
          predicates:
            - Path=/ws/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  jwt:
    secret: ${JWT_SECRET:Secret_key}
